language: node_js
notifications:
  email: false
sudo: false
node_js:
  - "0.12"
cache:
  directories:
    - node_modules
    - bower_components

before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install
script:
  - gulp lint
  - gulp build-prod
  - gulp test