language: node_js
notifications:
  email: false
node_js:
  - "0.12"
before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install
script:
  - gulp lint
  - gulp build-prod
  - gulp test